[phases.setup]
nixPkgs = ["python313", "postgresql.lib"]

[phases.install]
cmds = ["cd apps/post-ingestion && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step required'"]
